# Generated by Django 4.1.5 on 2023-01-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_id", models.CharField(max_length=100)),
                ("course_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
            ],
        ),
    ]
