# Generated by Django 4.1.5 on 2023-01-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(),
        ),
    ]
