# Generated by Django 4.1.5 on 2023-03-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chapter",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
