# Generated by Django 4.1.5 on 2023-04-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_delete_chapter_delete_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_scene",
                    models.CharField(db_index=True, max_length=200, null=True),
                ),
                ("id_bot", models.BigIntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="idrecord",
            constraint=models.UniqueConstraint(
                fields=("id_scene", "id_bot"), name="id_record_id_pair_unique"
            ),
        ),
    ]
