# Generated by Django 4.1.5 on 2023-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idrecord",
            name="activation_key",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
