# Generated by Django 4.1.5 on 2023-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_idrecord_activation_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="idrecord",
            name="activation_key_dt",
            field=models.DateTimeField(null=True),
        ),
    ]
