# Generated by Django 4.1.5 on 2023-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_idrecord_activation_key_dt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idrecord",
            name="activation_key",
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
