# Generated by Django 4.1.5 on 2023-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_auto_20230603_0804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idrecord",
            name="id_bot",
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="idrecord",
            name="id_scene",
            field=models.CharField(
                db_index=True, max_length=200, null=True, unique=True
            ),
        ),
    ]
