"""
Django settings for scene project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import json
from pathlib import Path
import os.path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def read_json_from_file(filepath):
    with open(filepath, "r") as f:
        return json.load(f)

conf = read_json_from_file( str(BASE_DIR / "conf.json") )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = conf.get("django_secret_key", "wellthatyourproblem")

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DJANGO_DEBUG", False))

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".senjun.ru"]
CSRF_TRUSTED_ORIGINS = ["https://*.senjun.ru"]

CSRF_FAILURE_VIEW = 'courses.views.csrf_failure'


# Application definition

INSTALLED_APPS = [
    "courses.apps.CoursesConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_prometheus",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'allauth.socialaccount.providers.vk',
    'allauth.socialaccount.providers.telegram',
    'captcha',
]

SITE_ID = 1

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

SOCIALACCOUNT_PROVIDERS = {
    'yandex': {
        'APP': {
            'client_id': conf.get("socialaccount", {}).get("yandex", {}).get("client_id", "client-id"),
            'secret': conf.get("socialaccount", {}).get("yandex", {}).get("secret", "secret"),
            'key': conf.get("socialaccount", {}).get("yandex", {}).get("key", "key")
        }
    },
    'vk': {
        'APP': {
            'client_id': conf.get("socialaccount", {}).get("vk", {}).get("client_id", "client-id"),
            'secret': conf.get("socialaccount", {}).get("vk", {}).get("secret", "secret"),
            'key': conf.get("socialaccount", {}).get("vk", {}).get("key", "key")
        }
    },
    'telegram': {
        'APP': {
            'client_id': conf.get("socialaccount", {}).get("telegram", {}).get("client_id", "client-id"),
            'secret': conf.get("socialaccount", {}).get("telegram", {}).get("secret", "secret")
        }
    }
}

ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ROOT_URLCONF = "scene.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.request',
            ],
        },
    },
]

ACCOUNT_FORMS = {'reset_password': 'courses.models.CaptchaResetPasswordForm'}

# DONT FORGET python manage.py createcachetable
# Used to rate limit mail sending in allauth
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}

# Allauth rate limits https://docs.allauth.org/en/latest/account/rate_limits.html
ACCOUNT_RATE_LIMITS = {
    "signup": "10/m/ip",
    "reset_password": "10/m/ip,5/m/key",
}

# https://django-simple-captcha.readthedocs.io/en/latest/
CAPTCHA_FONT_SIZE = 70
CAPTCHA_BACKGROUND_COLOR = "#6e84db"
CAPTCHA_FOREGROUND_COLOR = "#f5f5f5"
# CAPTCHA_LENGTH = 5
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_LETTER_ROTATION = (-20,20)

WSGI_APPLICATION = "scene.wsgi.application"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
"default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": conf.get("scene_db", {}).get("database", "scene"),
        "USER": conf.get("scene_db",{}).get("user", "senjun"),
        "PASSWORD": conf.get("scene_db", {}).get("password", "some_password"),
        "HOST": conf.get("scene_db", {}).get("host", "127.0.0.1"),
        "PORT": conf.get("scene_db", {}).get("port", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Admin page could be turned on for debug purposes on stage.
# It must be turned off on prod.
ADMIN_ENABLED = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = conf.get("static_root", "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_USE_SSL = True
EMAIL_HOST = conf.get("mail_for_user_registration", {}).get("host", "smtp.some.org") 
EMAIL_HOST_USER = conf.get("mail_for_user_registration", {}).get("email_address", "your_email") 
DEFAULT_FROM_EMAIL = conf.get("mail_for_user_registration", {}).get("email_address", "your_email") 
EMAIL_HOST_PASSWORD = conf.get("mail_for_user_registration", {}).get("host_password", "password") 
EMAIL_PORT = 465
EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
ACCOUNT_ACTIVATION_DAYS = 3

LANGUAGE_CODE = 'ru-ru'

LOGIN_REDIRECT_URL = "/courses"
LOGOUT_REDIRECT_URL = "/courses"
LOGIN_URL = "/login"

# Must be equal to the key in the bot service.
TG_BOT_KEY = conf.get("tg_bot_senjun", {}).get("key", "key")

INFRA_TG_BOT_TOKEN = conf.get("tg_bot_infra_alerts", {}).get("token", "token")
INFRA_TG_BOT_CHANNEL_ID = conf.get("tg_bot_infra_alerts", {}).get("channel_id", "channel_id")

COURSE_AUTHORS = read_json_from_file( BASE_DIR / "courses/static/courses/authors/courses.json")

def is_main_file(file_name, main_file_name):
    if main_file_name is not None:
        return file_name == main_file_name
    
    return file_name in ["main.cpp", "main.go", "Main.hs", "main.py", "main.rs"]
    

def get_project_structure(cur_obj, cur_path, main_file_name = None):
    cur_obj["name"] = os.path.basename(os.path.normpath(cur_path))

    if os.path.isfile(cur_path):
        with open(cur_path, 'r') as file:
            cur_obj["contents"] = file.read() # urlsafe_base64_encode(force_bytes(file.read()))

        if is_main_file(cur_obj["name"], main_file_name):
            cur_obj["is_main_file"] = True
        return

    if os.path.isdir(cur_path):
        cur_obj["children"] = []
        for child in os.listdir(cur_path):
            if child[0] == ".":
                continue
            cur_obj["children"].append({})
            get_project_structure(cur_obj["children"][-1], os.path.join(cur_path, child), main_file_name)


def get_default_playground_projects():
    root_playgrounds = BASE_DIR / "courses/static/courses/default_projects/"
    playgrounds = {}

    for item in os.listdir(root_playgrounds):
        full_path = os.path.join(root_playgrounds, item)
        if os.path.isdir(full_path):
            playgrounds[item] = {}
            get_project_structure(playgrounds[item], os.path.join(full_path, "project"))

    for k in playgrounds.keys():
        playgrounds[k] = json.dumps(playgrounds[k])
    
    return playgrounds

PLAYGROUND_PROJECTS = get_default_playground_projects()

